import type { Metadata } from "next";
import {Montserrat, Asap} from 'next/font/google'

import Header from "@/components/header/header";
import Footer from "@/components/footer/footer";

import "./globals.css";

const montserrat = Montserrat({
  subsets:['latin'],
  weight:['100', '200', '300', '400', '500', '600', '700', '800', '900'],
  variable:'--font-montserrat'
})

const asap = Asap({
  subsets:['latin'],
  weight:['100','200','300', '400', '500', '600', '700', '800','900'],
  variable:'--font-asap'
})



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className={`${montserrat.variable} ${asap.variable} `}>
      <Header />
        {children}
      {/* <Footer /> */}
        </body>
    </html>
  );
}
